# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-17 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=10, verbose_name='列车编号')),
                ('bus_num', models.CharField(max_length=10, unique=True, verbose_name='车牌号码')),
                ('start_time', models.DateTimeField(verbose_name='起始时间')),
                ('end_time', models.DateTimeField(verbose_name='到达时间')),
                ('start_city', models.CharField(max_length=128, verbose_name='起始城市')),
                ('end_city', models.CharField(max_length=128, verbose_name='到达城市')),
                ('start_station', models.CharField(max_length=128, verbose_name='始发车站')),
                ('end_station', models.CharField(max_length=128, verbose_name='到达车站')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('ticket', models.IntegerField(verbose_name='总票数')),
                ('standby_ticket', models.IntegerField(verbose_name='余票')),
            ],
            options={
                'verbose_name_plural': '车次表',
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('car_type', models.CharField(max_length=100, verbose_name='车型描述（品牌，名称，座位数）')),
                ('start_time', models.DateTimeField(verbose_name='出发时间')),
                ('start_city', models.CharField(max_length=128, verbose_name='起始城市')),
                ('end_city', models.CharField(max_length=128, verbose_name='到达城市')),
                ('price', models.IntegerField(null=True, verbose_name='价格')),
                ('seats', models.IntegerField(null=True, verbose_name='总座位数')),
                ('left_seats', models.IntegerField(null=True, verbose_name='剩余座位')),
            ],
            options={
                'verbose_name_plural': '拼车表',
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('num_list', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, '未完成'), (1, '已取消'), (2, '已完成')], default=0, verbose_name='订单状态')),
                ('list_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间')),
                ('list', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': '订单表',
                'db_table': 'list',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('phone', models.CharField(max_length=64, verbose_name='手机号')),
                ('is_active', models.IntegerField(default=1)),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('is_vip', models.IntegerField(default=0)),
                ('real_name', models.CharField(max_length=20, null=True, verbose_name='真实姓名')),
                ('id_num', models.IntegerField(null=True, unique=True, verbose_name='身份证号')),
                ('birthday', models.DateTimeField(null=True, verbose_name='生日')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='地址')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('pic', models.CharField(max_length=128, null=True)),
                ('gender', models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, null=True, verbose_name='性别')),
                ('car_num', models.CharField(max_length=10, null=True, unique=True, verbose_name='车牌号码')),
                ('user_uid', models.ForeignKey(blank=True, db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='App.User')),
            ],
            options={
                'verbose_name_plural': '用户详情',
                'db_table': 'userdetail',
            },
        ),
        migrations.AddField(
            model_name='list',
            name='list_uid',
            field=models.ForeignKey(blank=True, db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='App.User'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_uid',
            field=models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.User'),
        ),
    ]
