# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='管理员')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id_num',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
