# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='from_user',
            field=models.IntegerField(max_length=128, null=True),
        ),
    ]
